### ISSUE TITLE
Question around parallelInvocations

### ISSUE THREAD

**Issue by sseshachala** [alexcasalboni/aws-lambda-power-tuning#73] opened 2020-04-14 18:23 UTC
When i run the framework with parallelinvocation=false the invocation times are great - in millisecs interval. But when we run with the same flag = true - times are like in 100s of secs. Ours is busines critical app and need to be under 75 ms. Can you please explain a bit more around how parallelinvocation is implemented and what happens under the hood? Though reviewing code is easy, please share your thoughts and insights as well so we can learn and adjust our code accordingly.

**Comment by alexcasalboni** [comment] 2020-04-15 09:38
Hi @sseshachala, thanks for reaching out!

It sounds like your Lambda function depends on something else downstream that doesn't scale as well as Lambda? Are you calling a third-party API or a legacy backend? If that's true, it's likely that the performance of such system is impacted by the number of concurrent invocations, and that's why you see longer response times when `parallelinvocation` is enabled.

The goal of `parallelinvocation` is only to speed up the overall execution time. Also, I'd recommend using `parallelInvocation: true` only when you're fairly sure that each function execution will be independent and without side effects (or performance implications) on downstream services. On the other hand, if you expect a concurrent load of `X` invocations, you should probably try to fix the downstream dependency to avoid troubles when you deploy to production.

In a few words, this is what happens when you run Lambda Power Tuning with `parallelInvocation: true`, `powerValues: [128, 256, 512, 1024]`, and `num: 100` (for example):

1. Four aliases are created, one for each power configuration 
2. Four `Executors` will run in parallel, one for each power configuration
3. Each `Executor` will run your function 100 times in parallel - for a total of 400 concurrent executions (100 x 4)

The only major difference wrt `parallelInvocation: false` is in point (3): without parallel invocation you'd have at most 4 concurrent executions because each `Executor` will run your functions 100 times in series, one execution at a time. So this large difference is likely the cause of what you see (4 concurrent executions vs. 400 concurrent executions).

I hope this is useful. Let me know if you figure out the issue.

**Comment by sseshachala** [comment] 2020-04-27 18:37
Yes - we have some interesting numbers. Is there a way we can meet on skype ot MS teams meeting for few minutes?

**Comment by alexcasalboni** [comment] 2020-04-29 10:30
Sure, please DM me on [Twitter](https://twitter.com/alex_casalboni) or [LinkedIn](https://www.linkedin.com/in/alexcasalboni/).

**Comment by alexcasalboni** [comment] 2020-06-10 08:46
Closing this for now.

**Closed by alexcasalboni** 2020-06-10 08:46 UTC
